# Generated by Django 3.0.8 on 2020-08-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whatch',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_whatching', to='auctions.Listing'),
        ),
    ]
