# Generated by Django 3.0.8 on 2020-08-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_user_whatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whatch',
            field=models.ManyToManyField(blank=True, related_name='users_whatching', to='auctions.Listing'),
        ),
    ]
