# Generated by Django 3.0.8 on 2020-08-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200804_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whatch',
            field=models.ManyToManyField(blank=True, related_name='user_whatchlist', to='auctions.Listing'),
        ),
    ]
