# Generated by Django 3.0.8 on 2020-08-05 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20200804_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='whatch',
        ),
        migrations.AddField(
            model_name='user',
            name='whatchlist',
            field=models.ManyToManyField(blank=True, related_name='users_whatching', to='auctions.Listing'),
        ),
    ]
