# Generated by Django 3.0.8 on 2020-08-05 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200804_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='whatchlist',
            field=models.ManyToManyField(blank=True, related_name='users', to='auctions.Listing'),
        ),
    ]
