# Generated by Django 3.0.8 on 2020-08-06 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20200806_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='to_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_bids', to='auctions.Listing'),
        ),
    ]
