# Generated by Django 3.0.8 on 2020-08-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listing_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, help_text='Place a bid', max_digits=8),
        ),
    ]
